services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
